application: apt-momentum-728
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: puredj.wsgi.application
  login: admin

- url: /.*
  script: puredj.wsgi.application
